[workspace]
git_release_enable = false
git_tag_enable = false

[[package]]
name = "worktree-guard"
git_tag_name = "v{{ version }}"
git_tag_enable = true
git_release_enable = true
changelog_update = true
